"""
Common project constants
"""
THREAD_COUNT_DEFAULT = 10
STATUS_CODES_POSITIVE = [200, 204, 301, 302, 307, 401, 403]
STATUS_CODES_NEGATIVE = [404]
URL_FORMAT_BACKSLASH = "/"
URL_FORMAT_HTTP = "http://"
URL_FORMAT_HTTPS = "https://"
VERSION_NUMBER = "0.0.0"

# PROJECT FILE INDEX
FILEPATH_TEST_FILES_0_LINE_FILE = "./test_files/0_line_file.txt"
FILEPATH_TEST_FILES_1_LINE_FILE = "./test_files/1_line_file.txt"
FILEPATH_TEST_FILES_10_LINE_FILE = "./test_files/10_line_file.txt"
FILEPATH_TEST_FILES_100_LINE_FILE = "./test_files/100_line_file.txt"

# NON EXISTING RESOURCES
FILEPATH_TEST_FILES_DOES_NOT_EXIST = "./test_files/I_do_not_exist.txt"

# BROWSER NAMES
BROWSER_NAME_FIREFOX = "Firefox"
BROWSER_NAME_CHROME = "Chrome"
BROWSER_NAME_SAFARI = "Safari"
BROWSER_NAME_INTERNET_EXPLORER = "MSIE"
SUPPORTED_BROWSERS = [
    BROWSER_NAME_FIREFOX,
    BROWSER_NAME_CHROME,
    BROWSER_NAME_SAFARI,
    BROWSER_NAME_INTERNET_EXPLORER,
]
